### PR TITLE
Bionic fix for mariadb-backup package name.

### PR DESCRIPTION
**Pull request by shannonmitchell**
Looks like the version(-10.1) is part of the package name.

### CODE REVIEW

**Comment by BjoernT** [comment]
Strange: https://github.com/openstack/openstack-ansible-galera_server/blob/stable/train/vars/debian.yml#L56
 
please attach ```# apt-cache policy mariadb-backup-10.1
mariadb-backup-10.1:
  Installed: (none)
  Candidate: (none)
  Version table:```

```# apt-cache policy mariadb-backup
mariadb-backup:
  Installed: 1:10.3.13+maria~bionic
  Candidate: 1:10.3.13+maria~bionic
  Version table:
 *** 1:10.3.13+maria~bionic 1001
       1001 http://downloads.mariadb.com/MariaDB/mariadb-10.3.13/repo/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status```

so we can check where the issue comes from

**Comment by BjoernT** [comment]
Even updating to 10.3.18 seems fine and I still have a package under that name

```
# apt-cache policy mariadb-backup
mariadb-backup:
  Installed: 1:10.3.13+maria~bionic
  Candidate: 1:10.3.18+maria~bionic
  Version table:
     1:10.3.18+maria~bionic 1001
       1001 http://downloads.mariadb.com/MariaDB/mariadb-10.3.18/repo/ubuntu bionic/main amd64 Packages
 *** 1:10.3.13+maria~bionic 100
        100 /var/lib/dpkg/status
```

**Comment by shannonmitchell** [comment]
This is on the galera node for rocky while testing the upgrade maintenance plan.  

```
root@infra01-galera-container-77d10004:~# apt-cache policy mariadb-backup-10.1
mariadb-backup-10.1:
  Installed: 1:10.1.34+maria-1~bionic
  Candidate: 1:10.1.34+maria-1~bionic
  Version table:
 *** 1:10.1.34+maria-1~bionic 1001
       1001 http://downloads.mariadb.com/MariaDB/mariadb-10.1.34/repo/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
root@infra01-galera-container-77d10004:~# apt-cache policy mariadb-backup
N: Unable to locate package mariadb-backup
```

**Comment by shannonmitchell** [comment]
Looksl ike 10.3.18 with train has a '_' separating the mysqldb-backup as 10.1.34 with rocky has a '-' and .
```
mariadb-backup-10.1_10.1.34+maria-1~bionic_amd64.deb
mariadb-backup_10.3.18+maria~bionic_amd64.deb
```

**Comment by shannonmitchell** [comment]
I'm killing this PR.  Looks like something to account for the osa version would be needed if we are worried about rocy as well as train.

**Pull request closed without merging**
